### ISSUE TITLE
[Solargraph::FileNotFoundError] ApiMap did not catalog

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#139] opened 2019-01-14 12:57 UTC
What I did before this issue was renaming this file. After I rename this file I got:

```
[Error - 3:54:17 PM] Request textDocument/hover failed.
  Message: [Solargraph::FileNotFoundError] ApiMap did not catalog d:/ASPACK/FACILITY/gitsby/gitsby/db/migrate/20190114123505_create_subscription_packages.rb
  Code: -32603 
```

**Previous name was**: 20190114123505_create_subscriptions.rb
**New filename**: 20190114123505_create_subscription_packages.rb

See here: (watch the cursor position and logs)

![catalog-thread](https://user-images.githubusercontent.com/1711576/51114100-4e62fa00-1815-11e9-925b-86d399e11546.gif)

Related code:

```
Sequel.migration do
  change do
    create_table :subscription_packages do
      primary_key :id, type: :Bignum

      column :subject, 'character varying(64)', null: false
      column :slug, 'character varying(64)', null: false
      column :storage_size, 'bigint', null: false
      column :price_per_month, 'double precision', null: false
      column :price_per_year, 'double precision', null: false
      column :discount, 'smallint', default: nil
      column :discounted_until, 'timestamp without time zone', default: nil
      column :is_active, 'boolean', default: true
      column :properties, 'jsonb', default: nil

      column :actives_on, 'timestamp without time zone', default: nil
      column :expires_on, 'timestamp without time zone', default: nil
      column :created_on, 'timestamp without time zone', null: false
      column :updated_on, 'timestamp without time zone', default: nil
    end
  end
end
```

**Comment by castwide** [comment] 2019-01-14 14:46
I'm able to reproduce this one, but not consistently. There seems to be a window between renaming the file and the next ApiMap update during which the file is unrecognized.

Two questions:
1. Does hover start working again after a few seconds?
2. Does it work again if you close and reopen the file?

**Comment by gencer** [comment] 2019-01-14 15:09
> Does hover start working again after a few seconds?

No. Still broken.

> Does it work again if you close and reopen the file?

Yes. This fixes issue.

**Comment by gencer** [comment] 2019-01-14 15:45
I didn't see such error other than i reported here.

Currently, my issue goes away but i will keep eye on it. If raises again, I will also check other outputs and devtools.

**Comment by castwide** [comment] 2019-01-16 08:12
The master branch includes a change that might fix this issue. I reproduced it with the following steps:

1. Open a Ruby file in VS Code
2. Switch focus to a different file
3. Rename the Ruby file
4. Switch focus back to the Ruby file

The server would delete the file from both the workspace (if it's included) and the list of open files. The solution is to keep it in the list of open files as long as it's still in an editor window. This behavior is consistent with handling of other unmapped files in editors, e.g., a unit test that's excluded from the workspace. You can still use LSP features while you're editing it, but its definitions get ignored when you switch to a different file.

**Comment by castwide** [comment] 2019-01-22 15:42
Fix published in v0.31.1.

**Comment by davidbudnick** [comment] 2019-01-25 20:23
Still broken.

[Error - 2:22:27 PM] Request textDocument/hover failed.
  Message: [Solargraph::FileNotFoundError] ApiMap did not catalog c:/Users/david/Documents/Coding Projects/fs/InClass/ghostbusters/test/controllers/ghosts_controller_test.rb
  Code: -32603

**Comment by castwide** [comment] 2019-01-25 20:55
@davidbudnick Are you using 0.31.1?

Does it start working if you close and reopen the file? If so, can you reproduce the steps that made it stop working?

**Comment by davidbudnick** [comment] 2019-01-25 21:57
@castwide Looks like disabling and re-enabling the extension fixed the issue.

I will keep you posted if the issue happens again.

**Comment by MicMicMon** [comment] 2019-04-12 07:46
Happens to me, for example after checking out a new git branch which changes a bunch of files.

**Comment by gencer** [comment] 2019-04-12 12:53
Yes, same here too. Let say you run a rake task that generates a few files. This error occures. Same for if you delete file manually from Explorer while Solargraph is on.

**Comment by castwide** [comment] 2019-04-12 13:04
@MicMicMon @gencer Thanks for the details. I'll reopen this issue and dig further.

**Comment by castwide** [comment] 2019-05-04 19:55
The master branch includes a change that forces libraries to update their maps when the language server reports file events. This should fix FileNotFoundErrors that have been happening when external processes create or delete files.

**Comment by castwide** [comment] 2019-05-07 09:43
Released in v0.32.2.

**Comment by abraham** [comment] 2019-05-22 18:13
No further issues here.

**Comment by gencer** [comment] 2019-05-22 18:21
I also confirm that, I no longer see any error since release.

Thank you, Fred!

**Comment by alagos** [comment] 2019-05-29 00:46
I was using 0.32.3, I've just upgraded to 0.32.4 and I'm still seeing this problem:

```
[Error - 12:44:02 PM] Request textDocument/hover failed.
  Message: [Solargraph::FileNotFoundError] ApiMap did not catalog /Users/alter/workspace/my_project/lib/tasks/asset_import.rake
  Code: -32603 

```
quick review, it looks it's happening only with rake files.

**Comment by taylorthurlow** [comment] 2019-05-30 16:50
I've been getting it with what seems like just my files in my `/test` directory?
~~~
[Error - 9:47:45 AM] Request textDocument/hover failed.
  Message: [Solargraph::FileNotFoundError] ApiMap did not catalog /Users/taylor/Code/redacted/test/test_helper.rb
  Code: -32603 
~~~

**Comment by castwide** [comment] 2019-05-30 21:33
The next version of the gem will log FileNotFoundError for debugging purposes but will not send an error message to output. I'm also working on a way to correct the error in place instead of ignoring it, but this way at least it won't impact usability.

The change is currently in the master branch. I'll try to have it ready for publication tomorrow.

**Comment by minkir014** [comment] 2019-05-30 21:45
@castwide So you say you'll find the solution to correct the error instead of ignoring it in tomorrow publication.

**Comment by castwide** [comment] 2019-05-30 22:02
I'll ignore it either way, just to make sure the error doesn't annoy people by stealing focus in VS Code (or any other client). I hope to find a better long-term solution, but this should be good enough for now. The only side-effect is that hover and autocomplete might be temporarily unavailable while the server catalogs the new file. Cataloging is usually fast enough to be measured in milliseconds, but it looks like there are cases where the client can query the file before it's finished.

**Comment by castwide** [comment] 2019-05-31 21:34
Gem v0.32.5 is released. FileNotFoundErrors during completion and hover operations no longer steal focus in the client.

**Comment by alagos** [comment] 2019-06-13 23:46
I upgraded to 0.32.5, removed old versions, but still seeing the issue 😓 
```
[Error - 11:43:36 AM] Request textDocument/definition failed.
  Message: [Solargraph::FileNotFoundError] ApiMap did not catalog /Users/alter/workspace/my_project/test/unit/alert_test.rb
  Code: -32603 
```

**Comment by castwide** [comment] 2019-06-14 13:29
@alagos Some things that can help us debug:

1. If you're using a Ruby version manager like rvm or rbenv, it's possible that VS Code is using a different version than what you see on the command line. You can confirm whether the version in VS Code is correct by running `Solargraph: Get environment info` from the command palette.

2. When you get this error, is the `test/unit/alert_test.rb` open in an editor? Was it recently created, e.g., by a rake task?

3. What other extensions do you have installed? One of them might be triggering a request that the language server doesn't expect.

**Comment by alagos** [comment] 2019-06-18 03:25
I'm using rbenv, but I only have one ruby version. Even if I had another one, I only have installed `solargraph` on my current ruby version.
The files are only opened in vscode and they aren't new files. The only way I can think to make the files content change out of the editor is when I move to another branch, if that helps.

### Solargraph Environment Info

**System**

- Platform: x86_64-darwin18
- Shell: /bin/zsh
- Ruby Version: 2.2.10

**Solargraph**

- Solargraph Version: 0.32.5
- Core Documentation Version: 2.2.2
- Core Cache Directory: /Users/alter/.solargraph/cache
- Parser Target Version: 22
- Using Bundler: false

**Project**

- Config: {"completion"=>true, "hover"=>true, "symbols"=>true, "definitions"=>true, "rename"=>true, "references"=>true, "autoformat"=>false, "diagnostics"=>false, "formatting"=>false, "folding"=>true, "logLevel"=>"warn", "enablePages"=>true, "viewsPath"=>"/Users/alter/.vscode/extensions/castwide.solargraph-0.19.6/views", "transport"=>"socket", "externalServer"=>{"host"=>"localhost", "port"=>7658}, "commandPath"=>"solargraph", "useBundler"=>false, "bundlerPath"=>"bundle", "checkGemVersion"=>true}
- Workspace folders: ["/Users/alter/workspace/my_project"]

I've just generated a [settings sync gist](https://gist.github.com/alagos/a2ae1c10ea14a9895bbdb17a6eca7718) where appears all my extensions installed and also some configs. I've done in vscode.

**Comment by castwide** [comment] 2019-06-18 13:30
Gem 0.33.0 includes a fix that should help with this. The problem appears to be related to files that are either excluded from workspace maps, such as unit tests, or files from external libraries. There was a potential window where the language server's library would be out of sync: it would detect that the file was open before it was mapped. 0.33.0 makes sure the library is synchronized.

**Comment by castwide** [comment] 2019-06-21 11:06
Gem 0.33.2 introduces one more change that fixes FileNotFoundError in textDocument/references messages, and might finally eliminate the root cause.

The commonality between most/all the errors was a `checkout` method. Its purpose was to ensure that external files were synced with a library before querying its maps. The error would occur when `checkout` was called more than once in a single query.

There's already a mechanism in another component that performs much smarter library syncing, so the `checkout` method was not only unreliable, it was redundant. This version removes it altogether.

My one remaining concern is edge cases in processes that modify the workspace, such as switching repo branches or running rake tasks. Most of those cases should be fine, but I don't know what I don't know. If anyone still runs into this issue, please report it. In the meantime, the workaround is to restart either the language server or the editor that's running it.

**Comment by castwide** [comment] 2019-07-22 20:51
The errant workspace synchronization at the core of this issue is resolved, and cases that can be ignored emit a warning instead of stealing focus with an error. If anyone still encounters problems, please open a new issue.

**Closed by castwide** 2019-07-22 20:51 UTC
