### ISSUE TITLE
`process_comment_directives': invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by AlBundy33** [castwide/solargraph#474] opened 2021-08-16 06:10 UTC
An information about the file with the problem would be nice. :-)

```
Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/source_map/mapper.rb:200:in `process_comment_directives': invalid byte sequence in UTF-8 (ArgumentError)
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/source_map/mapper.rb:27:in `map'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/source_map/mapper.rb:50:in `map'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/source_map.rb:157:in `map'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:453:in `block in map!'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:452:in `each'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:452:in `map!'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/api_map.rb:119:in `load'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/shell.rb:177:in `block in scan'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/shell.rb:176:in `scan'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from Z:/dev_tools/Ruby30-x64/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/bin/solargraph:5:in `<top (required)>'
        from Z:/dev_tools/Ruby30-x64/bin/solargraph:23:in `load'
        from Z:/dev_tools/Ruby30-x64/bin/solargraph:23:in `<main>'
```

**Comment by castwide** [comment] 2021-09-19 16:50
Do any of your files contain characters that are not encoded for UTF-8?

I'll work on capturing that error so it identifies which file caused it. Fixing the root cause might be more difficult. Proper string handling across character sets is always an adventure.

**Comment by AlBundy33** [comment] 2021-09-19 17:29
yes, of course because my woekspace is not a single app it is more a collection of different scripts for different custumers from different developers. :-)

most files are already utf-8 but in this rare cases of different encodings it would be nice to have the path in the exception-message.

**Comment by castwide** [comment] 2021-09-19 18:29
I added exception handling so this particular error will report the name of the file where it occurred. It'll be included in v0.43.1, which I plan to release tomorrow morning.

I was also able to reproduce the error using a file with a known invalid byte sequence in the current tests (`spec/fixtures/invalid_byte.rb`), so I'll look into possible solutions for handling the unrecognized sequence gracefully instead of throwing an error.

**Comment by castwide** [comment] 2021-09-20 06:41
Version 0.43.1 reports filenames for this error.

**Comment by castwide** [comment] 2021-11-19 03:26
In version 0.44.1, `SourceMap::Mapper` handles invalid byte sequences more gracefully. (The main cause of the error was trying to run strings with invalid bytes through regular expressions.)

**Comment by castwide** [comment] 2022-06-01 16:11
Closing as resolved.

**Closed by castwide** 2022-06-01 16:11 UTC
