### ISSUE TITLE
bug: new infer to superclasss

### ISSUE THREAD

**Issue by SolaWing** [castwide/solargraph#279] opened 2020-02-15 04:19 UTC
```
class A < String
end

a = A.new('') # a infer to String, not A
```

**Comment by castwide** [comment] 2020-02-15 04:37
Confirmed. This appears to be specific to subclasses of `String`. If you change the first line to `class A < Integer` it works as expected.

I'm not sure of the root cause, but I'll add it to the roadmap.

**Comment by castwide** [comment] 2020-09-27 10:19
Fixed in v0.39.16.

**Closed** 2020-12-14 16:59 UTC
