### ISSUE TITLE
Symbol rename issue

### ISSUE THREAD

**Issue by whitebyte** [castwide/solargraph#107] opened 2018-11-19 14:18 UTC
Hi, I'm experiencing an issue with Solargraph symbol renaming. Consider this minimal example.rb:

```ruby
class TestClass
  SOME_CONST = 123
end
```

When I try to rename  `TestClass` to `TestClass2` it becomes `TTestClass2` instead. When I try to rename `SOME_CONST` to `SOME_CONST2` it becomes `SOMESOME_CONST2`.

I'm on Linux, Neovim, using https://github.com/autozimu/LanguageClient-neovim, Solargraph 0.28.4 started in stdio mode. I use exactly the same setup for various language servers with no issues, so I do believe it's related to Solargraph

**Comment by castwide** [comment] 2018-11-19 16:02
Confirmed. The same thing happens in the VS Code extension, so it looks like a problem in Solargraph itself. I'll look into it.

**Comment by castwide** [comment] 2018-11-19 16:32
The fix is in the master branch. I'll release it in version 0.29.0.

**Comment by whitebyte** [comment] 2018-11-20 08:48
Wow, that was fast! Closing then, thanks much

**Comment by whitebyte** [comment] 2018-12-02 13:32
Unfortunately, win 0.29.1 the problem persists. While it works OK for more simple cases (like my previous example), it fails when there is a namespace prefix:

```ruby
class Namespace::TestClass
  # whatever
end
```
Attempt to rename either a namespace part of a class part of the signature leads to malformed names

**Comment by castwide** [comment] 2019-02-22 13:11
Does this problem still exist with gem 0.31.3? I tested with gVim and vim-lsp. Given the following code:

```ruby
module Namespace; end
class Namespace::TestClass
end
obj = Namespace::TestClass.new
```

Using `:LspRename` to change `Namespace` to `OtherName` worked as expected in all three occurrences.

**Closed** 2019-04-04 11:26 UTC
Labels: bug
