### ISSUE TITLE
Workspace scan freezes

### ISSUE THREAD

**Issue by borisdrovnin** [castwide/solargraph#293] opened 2020-03-13 14:09 UTC
ruby version: 2.5.3
solargraph version: 0.38.4+
os: linux

The following example code freezes a workspace scan (`solargraph scan -v`) and causes 100% processor utilization.

```Ruby
@object = @object.a
@object = @object.b
@object = @object.c
@object = @object.d
@object = @object.e
@object = @object.f
@object = @object.g
@object = @object.h
@object = @object.i
@object = @object.g
```
Rollback to version 0.38.3 fixes the problem.

**Comment by castwide** [comment] 2020-03-20 05:34
Confirmed. It looks like type inference goes into an infinite loop. I'll investigate further.

**Comment by castwide** [comment] 2020-03-21 05:38
Fixed in the master branch. Slated for release in v0.38.6.

**Comment by castwide** [comment] 2020-03-23 02:53
Released in v0.38.6.

**Closed** 2020-04-22 23:09 UTC
