### ISSUE TITLE
How to specify YARD markup (Markdown)

### ISSUE THREAD

**Issue by zrzka** [castwide/solargraph#442] opened 2021-05-31 08:41 UTC
We have a documented code base with YARD and Markdown markup. Is there a way how to specify YARD markup? If not, will you accept a PR for it?

See the following screenshot (hover docs). Escaped characters, confused with ` ```ruby `, etc.

<details>
<summary>YARD docs screenshot = how YARD renders it (with --markup markdown), no issues</summary>

![image](https://user-images.githubusercontent.com/1084172/120165867-4b0d1500-c1fc-11eb-908d-713336394dd3.png)
</details>

<details>
<summary>Sublime Text & LSP & solargraph screenshot = ST hover, issues like escaped &lt;, etc.</summary>

![CleanShot 2021-05-31 at 10 34 12@2x](https://user-images.githubusercontent.com/1084172/120166016-768fff80-c1fc-11eb-90dd-ad908b10731a.png)

</details>

<details>
<summary>Code screenshot = source code for the previous two screenshots, no issues</summary>

<img width="701" alt="CleanShot 2021-05-31 at 10 34 42@2x" src="https://user-images.githubusercontent.com/1084172/120166072-84458500-c1fc-11eb-8383-9bca6c6058cd.png">

</details>

**Comment by castwide** [comment] 2021-05-31 13:39
Can you clarify what results you expect? I'm not sure what happened in that Sublime screenshot, but the Code screenshot looks correct to me.

I put together a simple reproduction. The code in the editor:

![markdown-render-1](https://user-images.githubusercontent.com/3704922/120201783-d03ffc00-c1f3-11eb-9483-a54ad5202414.png)

The rendered documentation in a hover:

![markdown-render-2](https://user-images.githubusercontent.com/3704922/120201842-de8e1800-c1f3-11eb-8b83-c0d031acde08.png)

**Comment by zrzka** [comment] 2021-05-31 13:46
What I do expect? Correctly rendered MD in the same way as YARD is rendering it (like the first screenshot - YARD docs screenshot). No escaped `<`, no ` ```ruby ` in the middle of code, etc.

Hmm, so, it should work. I'll try to find what triggers this behavior and will provide minimal reproducible example.

**Comment by castwide** [comment] 2021-05-31 14:03
Ah, so your Code screenshot is the hover? At first I assumed it was the editor window. My mistake. No idea why it's not rendering. If you can provide a reproducible example, I'll look into it.

**Comment by zrzka** [comment] 2021-05-31 14:11
Yep, _Sublime Text & LSP & solargraph_ is hover screenshot. Will work on MRE tmw.

**Comment by zrzka** [comment] 2021-05-31 14:27
(note to self, we're using _--markup markdown_ YARD arg to be able to generate docs properly)

**Comment by castwide** [comment] 2021-05-31 15:42
Just to be clear, your Code screenshot is what I'd expect from the editor window. Clients are responsible for rendering files in text editors. It's not a function of Solargraph or of language servers in general.

The Sublime hover screenshot is a different story. I'd expect the Markdown in the documentation to be formatted. I'm not sure if the issue is with Solargraph or Sublime/LSP, but I'll do what I can to help you troubleshoot it.

**Comment by zrzka** [comment] 2021-05-31 16:46
Sry for the confusion, I should have been more clear.

All screenshots represents the same thing. The Code one, which is perfect, no issues, is the source code used for other two screenshots - one is generated HTML via Yard (no issues) & the other one is ST hover (issues). The problematic one here is the ST hover only.

Again, my apologize if I wrote it in a confusing way.

**Comment by castwide** [comment] 2022-08-14 06:47
I'm closing this issue under the assumption that it was specific to Sublime. If there's something that still needs to be resolved in Solargraph, please feel free to reply or open a new issue.

**Closed by castwide** 2022-08-14 06:47 UTC
