### ISSUE TITLE
Undefined method `start' for nil:NilClass

### ISSUE THREAD

**Issue by ralius18** [castwide/solargraph#357] opened 2020-08-17 02:27 UTC
Running version 0.21.1

Error occurs when code completion is being used. For example, when typing a variable name, typing a method name or typing a hash parameter.

Code completion suggestions still appear, but error occurs at the same time

Full error message from '_Ruby Language Server_' every time:
```
Request textDocument/completion failed.
  Message: [NoMethodError] undefined method `start' for nil:NilClass
  Code: -32603 
```

**Comment by castwide** [comment] 2020-09-08 23:35
Sorry for the delay in replying.

I assume version 0.21.1 refers to the current version of the VS Code extension. The current version of the Solargraph gem is 0.39.15.

If you still experience this bug with the current version of the gem, please let me know. You also might get a stack trace of the error in VS Code's debug console (Help -> Toggle Developer Tools).

**Comment by ralius18** [comment] 2020-09-13 20:55
Have updated gem to 0.39.15, still getting the same problem.
Stack trace from console [here](https://pastebin.pl/view/76e8dd07)

**Comment by asilano** [comment] 2021-01-07 15:56
I'm also seeing the same problem, across Solargraph versions. I have an essentially identical backtrace - `notify_observers` leading through to `complete` and ending with the nested calls in `parser/rubyvm/class_methods.rb:133` and `:134`.

I am running VSCode on Windows 10, editing files on WSL. Solargraph is at 0.40.1. I have tried switching to external transport and explicitly running `solargraph socket` in WSL, which also fails the same way.

**Comment by castwide** [comment] 2021-09-27 09:38
Possibly related: #463

**Comment by castwide** [comment] 2022-05-22 06:52
Closing this issue as a duplicate of #463. It's almost certainly related to parsing interpolated string ranges. If the problem still persists in spite of the other change, please feel free to reopen or post a new issue.

**Closed by castwide** 2022-05-22 06:52 UTC
