### ISSUE TITLE
Does not work with Fish Shell

### ISSUE THREAD

**Issue by richjdsmith** [castwide/solargraph#104] opened 2018-11-13 10:20 UTC
I installed the Fish Shell yesterday. That is the only thing that has changed, but now Solargraph in VS Code is no longer able to find the installed gem. Gem List shows `solargraph (0.28.4, 0.28.3, 0.28.2, 0.28.1, 0.28.0, 0.26.1, 0.24.1, 0.23.5, 0.23.3, 0.23.2, 0.22.0)` but no luck using the plugin.

**Comment by castwide** [comment] 2018-11-13 22:09
Closing as duplicate of castwide/vscode-solargraph#85

**Closed by castwide** 2018-11-13 22:09 UTC
