### ISSUE TITLE
Require from gem

### ISSUE THREAD

**Issue by sphynx79** [castwide/solargraph#11] opened 2017-10-20 22:18 UTC
Hi i have one question!

This gem support also completion from require gem, or check Gemfile for include completion also for gem that i you

Thanks

**Comment by castwide** [comment] 2017-10-21 00:17
Yes to the first, not yet to the second.

Solargraph will parse your code's `require` statements and look for corresponding gems. If it finds one, it will use YARD to generate completions.

An option to automatically include gems listed in your Gemfile should be forthcoming. I'm still working out the details.

Some things to note:
* The standard library is not supported yet. The `require` has to refer to an external gem for Solargraph to find it. (Standard library support is hopefully forthcoming.)
* Some gems, most notably Rails, depend on a lot of magic that reduces Solargraph's ability to provide useful suggestions.
* The `require` needs to be given a literal string for Solargraph to find the gem. `require 'bundler'` will work, but `path = 'bundler'; require path` will not.

**Comment by castwide** [comment] 2017-10-30 09:32
The latest version (0.13.1) will automatically map all bundled gems if it finds `require 'bundler/setup'` in your workspace code.

**Comment by AndyBay** [comment] 2017-12-04 14:15
Seems like Solargraph no longer finds required gems/ files.
Also when requiring `Benchmark`, the class/ module doesn't get found but if you type out `benchmark.` you get suggestions as normal even if you don't require it.

![require_std](https://user-images.githubusercontent.com/1170184/33556610-cd7c35dc-d904-11e7-988f-e6d3936739ae.png)

**Comment by castwide** [comment] 2017-12-04 14:52
Confirmed there's a partial issue with required gems. I created a new .rb file in an empty project with `require 'parser'`. First suggestion results for `P` didn't find Parser, but it worked correctly after I saved the file.

![image](https://user-images.githubusercontent.com/3704922/33557838-5a36a4d2-d8d6-11e7-9cd4-f6e0c99499fb.png)

Can you confirm whether saving the file makes it work? It'll still need fixed so the `require` gets picked up during editing, but I want to make sure you're seeing the same behavior.

As for `Benchmark`, support for the Ruby stdlib comes with a few caveats. Solargraph can't detect the source from the `require` path, so it doesn't find the namespace until you've written the whole name. This is partially due to major lag that can result from including the entire stdlib in searches. Besides being slow, Solargraph would be forced to assume that anything in the stdlib is part of your project, even if you didn't require it (Benchmark, YAML, Net, etc.). The current behavior is a compromise: it doesn't autocomplete the top-level namespace, but assumes you want it if you write the whole name.

I'm looking for ways to make stdlib support smarter. One possibility is to compare lower-case stdlib namespaces to require paths, e.g., only pull the Benchmark suggestion when `require 'benchmark'` exists. That might cover at least a good portion of use cases.

**Comment by AndyBay** [comment] 2017-12-04 17:21
Tried again, after saving the file a few times. No change. Also tried on a different machine, but I get the same behaviour.

**Comment by castwide** [comment] 2017-12-04 17:54
Okay. There are a few things we can troubleshoot.

* What OS are you using?

* What version of the Solargraph gem and extension? (Latest are 0.15.1 and 0.10.2 respectively)

* Did you change any user/workspace settings, e.g., `solargraph.useBundler`?

* If you save the file with `require 'parser'` and reopen VS Code, does it still not work?

* Can you confirm that the parser gem is available? Solargraph tries to run the server using your workspace as the cwd. Depending on how you open VS Code, it might use your system installation of Ruby or the installation configured for the workspace via rvm/rbenv/whatever. One way to check is to run irb from VS Code's integrated terminal. If `require 'parser'` works from there, Solargraph should be able to see the gem.

**Comment by AndyBay** [comment] 2017-12-04 22:51
Managed to get `parser` to work now by creating a new workspace, will have to debug later why my normal workspace has problems here. My workspace settings are empty, so not sure what the problem is.

Always using the latest versions.

**Comment by castwide** [comment] 2017-12-05 00:24
Thanks for the update. If you happen to determine a root cause, please let me know.

At any rate, I definitely found a minor bug in required path handling. It might be coincidental instead of related to your problem, but either way the fix will be included in the next version.

**Comment by AndyBay** [comment] 2017-12-08 02:38
Tested a bit around with my workspace file/ creating new workspaces and it seem like it's a multi root issue in VS Code when you `require` local files. If I work in the "top" workspace folder, Solargraph parses the other ruby files in that root folder as normal, but if I move that root folder down in the workspace file, then Solargraph parses only the file you're currently working on.

Requiring other gems, like `parser`, seems to work good now. Not dependent on root workspace folder placement.

**Comment by castwide** [comment] 2017-12-08 14:56
Good to know, thanks. Multi-root workspace support is on the roadmap (https://github.com/castwide/vscode-solargraph/issues/15).

Solargraph usually maps the entire workspace regardless of local `require`s. Any class or module definition will be visible from any file. It's not always a perfect representation of the namespaces as they'll exist at runtime, but it seems like the most practical assumption. The `include` and `exclude` settings in .solargraph.yml modify the mapping rules. (Note that the file you're currently editing should get included in the map even if the settings exclude it while editing other files.)

Multi-root workspaces introduce some interesting caveats. I'm not sure what the rules will be, but I'm open to suggestions.

**Closed** 2018-01-23 12:13 UTC
Labels: question
