### ISSUE TITLE
latest solargraph collide with rspec causing error with formatters

### ISSUE THREAD

**Issue by MuhmdRaouf** [castwide/solargraph#331] opened 2020-06-15 15:00 UTC
Hey, I am working on old rails project when added solargraph to Gemfile it installs an old version so  I am currently using:

```
solargraph (0.35.2)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.2)
rspec-mocks (3.8.0)
rspec-rails (3.8.2)
rspec-snapshot (0.1.2)
rspec-support (3.8.0)
rspec_junit_formatter (0.4.1)
```
it works fine, but vscode asked me to update solargraph and  when I updated to latest `solargraph (0.39.8)` whenever I run rspec command I am facing the following error:

```
Coverage report generated for RSpec to /Users/snowflake/ko/ko-server/coverage. 0.0 / 0.0 LOC (100.0%) covered.
/Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/formatters.rb:210:in `require': cannot load such file -- rspec/core/formatters/progress_formatter (LoadError)
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/formatters.rb:210:in `built_in_formatter'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/formatters.rb:180:in `find_formatter'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/formatters.rb:150:in `add'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/formatters.rb:125:in `setup_default'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:47:in `block in prepare_default'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:228:in `ensure_listeners_ready'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:199:in `notify'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:92:in `message'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:161:in `notify_non_example_exception'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2037:in `rescue in load_file_handling_errors'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in `load_file_handling_errors'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in `block in load_spec_files'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `each'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `load_spec_files'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in `setup'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in `run'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/bin/rspec:23:in `load'
        from /Users/snowflake/.config/rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
```

can someone help me to get it working, and is it worth it to update or the old version of solargraph is just fine !?

I don't know if it that would help, but that's the  latest install log:

```
snowflake in ko-server on  master [$!] via ⬢ v12.16.3 via 💎 v2.3.1 took 46s
[I] ➜ gem install solargraph
Fetching maruku-0.7.3.gem
Fetching benchmark-0.1.0.gem
Fetching e2mmap-0.1.0.gem
Fetching solargraph-0.39.8.gem
Fetching mini_portile2-2.4.0.gem
Fetching nokogiri-1.10.9.gem
Fetching thor-1.0.1.gem
Successfully installed benchmark-0.1.0
Successfully installed e2mmap-0.1.0
Successfully installed maruku-0.7.3
Successfully installed mini_portile2-2.4.0
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.9
Successfully installed thor-1.0.1
Successfully installed solargraph-0.39.8
Parsing documentation for benchmark-0.1.0
Installing ri documentation for benchmark-0.1.0
Parsing documentation for e2mmap-0.1.0
Installing ri documentation for e2mmap-0.1.0
Parsing documentation for maruku-0.7.3
Installing ri documentation for maruku-0.7.3
Parsing documentation for mini_portile2-2.4.0
Installing ri documentation for mini_portile2-2.4.0
Parsing documentation for nokogiri-1.10.9
Installing ri documentation for nokogiri-1.10.9
Parsing documentation for thor-1.0.1
Installing ri documentation for thor-1.0.1
Parsing documentation for solargraph-0.39.8
Installing ri documentation for solargraph-0.39.8
Done installing documentation for benchmark, e2mmap, maruku, mini_portile2, nokogiri, thor, solargraph after 11 seconds
7 gems installed
```

**Comment by castwide** [comment] 2020-06-16 10:14
I've seen this happen on a couple of other projects. I'm not sure of the root cause, but one workaround is to run `bundle exec rspec` instead.

**Comment by MuhmdRaouf** [comment] 2020-06-16 11:07
I can confirm that running `bundle exec rspec` worked, hope we can know what is the main cause tho so we can solve it, and i would love to help to do so just let me know what i can do to help and i will do it

**Comment by castwide** [comment] 2020-12-19 19:16
As far as I can tell, this is a general issue with RSpec that happens when the version loaded by the test suite conflicts with the version installed in the system gems, possibly because `spec_helper.rb` invokes Bundler and loads a different RSpec than the one that was executed from the command line.

Since it doesn't appear to be specific to Solargraph, I'm going to close this issue. Please feel free to comment or reopen if it turns out to be a Solargraph issue after all.

**Closed by castwide** 2020-12-19 19:16 UTC
