### ISSUE TITLE
Argument errors while generating gem cache with `solargraph bundle`

### ISSUE THREAD

**Issue by arbox** [castwide/solargraph#315] opened 2020-04-29 13:31 UTC
Thank you for the great efforts with Solargraph!

After update to `0.39.3` and running  `solargraph bundle` in a Rails project I get the following error:
![image](https://user-images.githubusercontent.com/357237/80601640-5ce71c00-8a2e-11ea-837e-e14068abd710.png)

It's probably something small :)

I've tried `0.38.6` and it works. Every version after `0.38.6` is affected.

**Comment by castwide** [comment] 2020-04-29 14:48
Thanks!

I confirmed the bug and found the root cause. I'll have a fix for it in the next patch release.

**Comment by castwide** [comment] 2020-05-01 07:37
Fixed in gem v0.39.4.

**Comment by arbox** [comment] 2020-05-01 10:25
I confirm that the version `0.39.4` is not affected any more.

Thank you a lot! Your Solargraph and Emacs LSP make me really productive!

**Closed** 2020-06-03 08:59 UTC
Labels: bug
