### ISSUE TITLE
This way of documenting a dynamically generated class breaks Solargraph

### ISSUE THREAD

**Issue by Hubro** [castwide/solargraph#183] opened 2019-05-10 12:22 UTC
The following class (`Kartverket::Address`) makes Solargraph spam errors in the Output panel any time I'm working with an instance of the class. Since I can't stop the Output panel from opening, this is extremely distracting and annoying.

```ruby

require "values"

module Kartverket
  Address = Value.new(
    :street_name, :house_number, :letter, :postal_code, :city,
    :municipality, :municipality_number, :county,
    :latitude, :longitude
  )

  # A Norwegian street address, as defined by Kartverket
  #
  # @!attribute street_name
  #   @return [String]
  #
  # @!attribute house_number
  #   @return [Integer]
  #
  # @!attribute letter
  #   @return [String]
  #
  # @!attribute postal_code
  #   @return [Integer]
  #
  # @!attribute city
  #   @return [String]
  #
  # @!attribute municipality
  #   @return [String]
  #
  # @!attribute municipality_number
  #   @return [Integer]
  #
  # @!attribute county
  #   @return [String]
  #
  # @!attribute latitude
  #   @return [Float]
  #
  # @!attribute longitude
  #   @return [Float]
  #
  class Address
    # Returns a string representation of the address
    #
    # @return [String]
    #
    def to_s
      "#{street_name} #{house_number}#{letter}, #{postal_code} #{city}"
    end
  end
end
```

Here's a sample output of the errors:

```
[Error - 2:19:02 PM] Request textDocument/completion failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:03 PM] Request textDocument/completion failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:07 PM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:10 PM] Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:17 PM] Request textDocument/completion failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:17 PM] Request textDocument/completion failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603 
[Error - 2:19:18 PM] Request textDocument/signatureHelp failed.
  Message: [NoMethodError] undefined method `type' for #<Solargraph::Pin::Constant:0x0000564a87e2beb8>
  Code: -32603
```

**Comment by castwide** [comment] 2019-05-10 14:30
Confirmed. The problem appears to be the `Address` constant assignment in combination with the class definition. If the code only uses one or the other, the error doesn't happen.

**Comment by minkir014** [comment] 2019-05-10 16:15
I didn't what you have said. Is the problem in the extension or the class?

**Comment by castwide** [comment] 2019-05-10 16:57
At least part of the problem is in the extension. Here are minimum examples to demonstrate what I meant:

```ruby
# Constant assignment works
module Kartverket
  Address = Value.new
end
```

```ruby
# Class definition works
module Kartverket
  class Address; end
end
```

```ruby
# Both together cause an error
module Kartverket
  Address = Value.new
  class Address; end
end
```

I don't know if the way you're using them together is correct because I don't know how the `Value` class works. If `Value.new` doesn't return another class, the class definition should throw a `TypeError` when you run the script.

But even if the code is invalid, Solargraph should treat `Address` as an unknown type without throwing an error.

**Comment by Hubro** [comment] 2019-05-10 17:14
@castwide `Value.new` does indeed return a class

**Comment by minkir014** [comment] 2019-05-10 21:29
You can see how the ruby side extension for vs code manages this. It doesn't have this issue.

**Comment by castwide** [comment] 2019-05-11 04:21
Thanks, @Hubro. Resolving the `Address` type from both definitions might be a little tricky, but at least I can get rid of the error.

@minkir014 What ruby side extension?

**Comment by minkir014** [comment] 2019-05-11 18:45
Sorry I meant ruby ide extension.

**Comment by castwide** [comment] 2019-05-11 19:36
Gotcha. Unfortunately, the problem was specific to code mapping features that don't have an equivalent in rubyide/vscode-ruby.

On the plus side, I have a fix. It's pushed to the master branch and I expect to release a new gem early next week.

**Comment by castwide** [comment] 2019-05-14 10:19
Released in gem v0.32.3.

**Comment by Hubro** [comment] 2019-05-14 11:06
I'm on vacation this week but I'll test it out ASAP.

**Comment by castwide** [comment] 2019-06-23 00:40
Closing as fixed.

**Closed by castwide** 2019-06-23 00:40 UTC
